version: '3'
services:
    kong:
        build:
            context: ./kong
            dockerfile: Dockerfile

        environment:
            KONG_DATABASE: "off"
            KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
            KONG_PLUGINS: "kong-jwt2header,rate-limiting,route-by-header"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://kong:8000"]
            interval: 5s
            timeout: 2s
            retries: 15
        ports:
            - 8000:8000
    service-a:
        hostname: service-a
        image: strm/helloworld-http
    service-b:
        hostname: service-b
        image: strm/helloworld-http
    service-ring-0:
        hostname: service-ring-0
        image: strm/helloworld-http
