version: '3'
services:
    kong:
        build:
            context: .
            dockerfile: ./kong/Dockerfile

        volumes:
            - kong:/etc/kong/
        environment:
            KONG_DATABASE: "off"
            KONG_DECLARATIVE_CONFIG: kong.yml
        healthcheck:
            test: ["CMD", "curl", "-f", "http://kong:8000"]
            interval: 5s
            timeout: 2s
            retries: 15
        ports:
            - 8000:8000
            - 8001:8001
            - 8443:8443
            - 8444:8444
    service-a:
        hostname: service-a
        image: strm/helloworld-http
    service-b:
        hostname: service-b
        image: strm/helloworld-http

volumes:
    kong: