version: '3'
services:
    load-balancer:
        build:
            context: load-balancer
            dockerfile: Dockerfile
        command: nginx -g 'daemon off;'
        depends_on:
            - service-a
            - service-b
        restart: always
        ports:
            - 80:80
        volumes:
            - ./load-balancer:/logs
        environment:
            - "NODES=service-a:80 service-b:80"
    service-a:
        hostname: service-a
        image: strm/helloworld-http
    service-b:
        hostname: service-b
        image: strm/helloworld-http