version: '3'
services:
    kong:
        image: kong_nodb:latest
        environment:
            KONG_DATABASE: "off"
            KONG_DECLARATIVE_CONFIG: kong.yml
        healthcheck:
            test: [“CMD”, “curl”, “-f”, “http://kong:8000”]
            interval: 5s
            timeout: 2s
            retries: 15
        ports:
            - 8000:8000
            - 8001:8001
            - 8443:8443
            - 8444:8444
    load-balancer:
        build:
            context: load-balancer
            dockerfile: Dockerfile
        command: nginx -g 'daemon off;'
        depends_on:
            - service-a
            - service-b
        restart: always
        ports:
            - 80:80
        volumes:
            - ./load-balancer:/logs
        environment:
            - "NODES=service-a:80 service-b:80"
    service-a:
        hostname: service-a
        image: strm/helloworld-http
    service-b:
        hostname: service-b
        image: strm/helloworld-http